# yaml-language-server: $schema=https://static.codemagic.io/codemagic-schema.json
workflows:
  ios-workflow:
    name: iOS Production
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - appstore_credentialsAC
      
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.winedge.app
      
      vars:
        BUNDLE_ID: "io.winedge.app"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      
      xcode: latest
      node: 20
    
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Capacitor sync
        script: |
          npx cap sync ios
      
      - name: Initialize keychain
        script: |
          keychain initialize
      
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Increment build number
        script: |
          cd ios/App
          # Forcer le build number à 2 (changez ce nombre pour chaque nouvelle version)
          BUILD_NUMBER=2
          echo "Setting build number to $BUILD_NUMBER"
          xcrun agvtool new-version -all $BUILD_NUMBER
          # Vérifier
          echo "Current build number:"
          xcrun agvtool what-version
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - groupsoiby@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        submit_to_testflight: true
        submit_to_app_store: false